language: c

env:
  - R_LIBS_USER=~/R R_PKG="$(basename $TRAVIS_REPO_SLUG)"

install:
  - sudo apt-add-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update -qq
  - sudo apt-get install r-base-dev r-cran-devtools r-cran-rcurl
  - "[ ! -d ~/R ] && mkdir ~/R"
  - Rscript -e "options(repos = 'http://cran.rstudio.org'); devtools::install_deps('.', dep = TRUE)"

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check *.tar.gz --no-manual
